version: 0.0
os: linux
files:
  - source: /css
    destination: /var/www/html/
  - source: /images
    destination: /var/www/html/
  - source: /js
    destination: /var/www/html/
  - source: /about.html
    destination: /var/www/html/
  - source: /contact.html
    destination: /var/www/html/
  - source: /cycle.html
    destination: /var/www/html/
  - source: /index.html
    destination: /var/www/html/
  - source: /news.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install_dependencies.sh
          pattern: "*"
          mode: +x
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install.sh
          pattern: "*"
          mode: +x
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/start_server.sh
          pattern: "*"
          mode: +x
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/stop_server.sh
          pattern: "*"
          mode: +x