apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dellawills
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/denishjackson1/dellawillent.git
    path: kube-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true