apiVersion: apps/v1
kind: Deployment
metadata:
  name: dellawills
  labels:
    name: dellawills
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dellawills
  template:
    metadata:
      labels:
        app: dellawills
    spec:
      containers:
      - name: dellawills-container
        image: denishjackson/dellawills:latest