apiVersion: apps/v1
kind: Deployment
metadata:
  name: basictest-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: basictest
  template:
    metadata:
      labels:
        app: basictest
    spec:
      containers:
      - name: basictest
        image: emmamichael/agocdproject:latest
        ports:
        - containerPort: 9000