apiVersion: apps/v1
kind: Deployment
metadata:
  name: dellawills-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dellawills
  template:
    metadata:
      labels:
        app: dellawills
    spec:
      containers:
      - name: dellawills
        image: denishjackson/dellawills:latest
        ports:
        - containerPort: 9000