name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull denishjackson/dellawills:latest
    - name: Delete old docker container
      run: sudo docker rm -f dellawills-container || true
    - name: Run Doocker Container
      run: sudo docker run -d -p 8080:8080 - name dellawills-container denishjackson/dellawills
